env:
    - PIO_FIRMWARE_URL="http://foo.bar/firmware.com"
    - PIO_MQTT_HOST_IP=127.0.0.1
    - PIO_MQTT_PORT=1883
    - PIO_MQTT_TOPIC=topic

language: python
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

before_script:
    - cp platformio.ini.dist platformio.ini

install:
    - pip install -U cpplint
    - pip install -U platformio
    - platformio update

script:
    - cpplint --recursive src include lib test
    - platformio run
